### ISSUE TITLE
Unsolicited email

### ISSUE THREAD

**Issue by Exagone313** [elsoul/skeet-cli#131]
Please refrain from sending unsolicited emails using my commit email advertising this repository.

As a European citizen, you cannot process my personal data without my prior explicit consent. I hereby ask you to remove any personal data you might have concerning me.

**Comment by POPPIN-FUMI** [comment]
Sorry if you feel bad about it.
Your information was on your Github profile page. I won't email you again.
Best Regards.

**Comment by Exagone313** [comment]
My email address was never displayed publicly on my GitHub profile. It is only available when checking the commits I have made on my repository.

**Comment by POPPIN-FUMI** [comment]
It is displayed on your profile page. I can send you a screenshot if you want.

**Comment by KishiTheMechanic** [comment]
@Exagone313 I apologize for the inconvenience caused. We had no intention of misusing your personal information. Your email address was listed on your GitHub profile, which led me to believe it was publicly available. We will make sure to remove any personal data concerning you and will not contact you again via email. However, you may want to check your GitHub settings as your email address is visible there.

**Comment by Exagone313** [comment]
This was an overlook on my part. It was hidden when not logged in to GitHub and I supposed it was private. Thank you.

**Comment by Sculas** [comment]
Please stop sending unsolicited emails. If you want to advertise your repository, invest in something like Google Ads, but not this. I hereby ask you to remove any data you have related to me as well.

**Comment by tlhunter** [comment]
Note that having a publicly displayed email address does not mean that any spam sent to that address is no longer spam.

This is a classic case of victim shaming and gaslighting.
