### ISSUE TITLE
Spam email asking to star this repo 

### ISSUE THREAD

**Issue by tlhunter** [elsoul/skeet-cli#147]
Here's an unsolicited email I received asking me to star this repository:

```
Dear tlhunter,

I hope this message finds you well.
My name is Kawasaki and I'm a founder of ELSOUL LABO B.V.,
We created a new open-source modern framework.

Firstly, I'd like to express our sincere gratitude for showing interest in graphql-js by starring it on GitHub. Your recognition speaks volumes, given your expertise and considerable influence in the tech community.

Understanding the importance of feedback and insights from experts like you, we are reaching out with a humble request.
We would be honored if you could take some time to review our framework and provide us with your invaluable feedback.
Your insights would be crucial in helping us enhance its capabilities and make it more beneficial for the community.

Here's the link to our GitHub repository: https://github.com/elsoul/skeet-cli

We understand you have a busy schedule, but any feedback or suggestions you can provide would be greatly appreciated.
If you have any questions or need further information, please don't hesitate to reach out.

Thank you in advance for considering our request.
We're looking forward to hearing from you.

Warm regards,
Fumitake Kawasaki
CEO ELSOUL LABO B.V.
https://labo.elsoul.nl
```

This is spam and should not be happening.

**Comment by KishiTheMechanic** [comment]
I understand that you were displeased with the unsolicited email you received from us regarding our new open-source framework. We deeply apologize for any inconvenience or discomfort we may have caused.

Our aim was to gather valuable insights from experts in the field like you, but we now realize that our approach was inappropriate.

Please rest assured that you will not receive any more emails from us going forward. 

We are taking steps to ensure that this does not happen again and appreciate your understanding.

Best regards,
Shota Kishi

**Comment by tlhunter** [comment]
> Please rest assured that you will not receive any more emails from us going forward.

That _I_ will not receive more emails, or _anyone_ will not receive more emails?
