### ISSUE TITLE
Unsolicited email in violation of GH policy

### ISSUE THREAD

**Issue by nilium** [elsoul/skeet-cli#149]
I received unsolicited email from the organization behind this repository using the username and email associated with my GitHub account. This is in violation of the acceptable use policies of GitHub forbidding the use of user information for sending unsolicited email.

Refer to the acceptable use policies for detail: https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#7-information-usage-restrictions

> You may not use information from the Service (whether scraped, collected through our API, or obtained otherwise) for spamming purposes, including for the purposes of sending unsolicited emails to users or selling personal information, such as to recruiters, headhunters, and job boards.

In the interest of ensuring GitHub can act as the mediator in this (because the maintainers of this repo are still doing this, as seen by the past issues they've closed over this), I've reported the organization to GitHub as well for this abuse. I encourage anyone else receiving the same unsolicited emails to do the same.

**Comment by KishiTheMechanic** [comment]
I apologize for the unsolicited communication you recently received from us regarding our new open-source framework. We understand that our outreach may have caused you inconvenience or annoyance.

The intention was to engage with field experts like yourself for valuable feedback, but we acknowledge that our method was not well-considered.

We have taken measures to ensure that you won't receive unsolicited emails from us in the future.

Thank you for your understanding as we work to improve our communication approach.

Sincerely,
Shota Kishi

**Comment by nilium** [comment]
@hut8 Please make sure to report this using the [report abuse](https://github.com/contact/report-abuse?report=elsoul)  link under https://github.com/elsoul to let GitHub know.
