### ISSUE TITLE
Another request to refrain from spamming other users.

### ISSUE THREAD

**Issue by Faeranne** [elsoul/skeet-cli#155]
You have sent out a form letter repeatedly to different developers.  This is very unacceptable behavior, and you've been asked several times to cease, but have continued to do so.  Please cease sending *any* unsolicited emails to *anyone*.  This is not how the community works, and you are painting a very negative light on yourself and your project by doing so.  There are other ways to request feedback or show the community your work (talk with media, post to reddit or hacker news, etc).  Skimming public pages and sending unprompted emails is not acceptable, regardless of if emails are public or not, and especially when the email being sent is untargeted.  It's very obvious you used a mail-merge and simply blasted out tons of emails, as the emails contain several instances of `undefined` within the text.  Note that your continued insistence on sending these emails has already encouraged myself and others to start reporting your account for spam, and there is a very good chance that continuing to send like this will result in issues.

Remember to respect the community, and the community will respect you.

**Comment by KishiTheMechanic** [comment]
First and foremost, I want to extend my sincerest apologies for the unsolicited emails you have received from us.

My only intention was to seek constructive feedback on a framework we’ve been working on. While my intentions were not malicious, I now understand that my approach was misguided.

Effective immediately, I'm halting this unsolicited email and will look into more respectful ways to share our work and seek feedback.

Thank you for calling this to my attention; it's a lesson I take to heart. I understand the inconvenience and discomfort our actions may have caused and we're committed to doing better moving forward.

Best regards,
Shota Kishi

**Comment by bruchmann** [comment]
> Effective immediately, I'm halting this unsolicited email and will look into more respectful ways to share our work and seek feedback.

I received a mail from you 20 minutes ago.
