### ISSUE TITLE
Please don't spam

### ISSUE THREAD

**Issue by jquast** [elsoul/skeet-cli#158]
I would thank you not to send unsolicited spam e-mail. I don't believe that you "stumbled" upon my github profile as I've never worked with any of you.

This kind of behavior is befitting only to scammers and spammers. Please don't do it again.

> Dear jquast,
> 
> I stumbled upon your email while looking at your GitHub profile and decided to reach out.
> Wishing you the best. This is Kishi, from ELSOUL LABO B.V.
> 
> Appreciating the wisdom and feedback from renowned professionals like yourself, we earnestly ask for your expert review.
Your time and insights on our serverless framework would be highly valued and respected.
> 
> Your constructive criticisms and suggestions will be instrumental in optimizing our serverless framework for the betterment of the tech ecosystem.
Please access our GitHub repository using the following link: https://github.com/elsoul/skeet-cli
> 
> We appreciate the demands of your busy schedule, but would be grateful for any feedback or advice you can offer.
Should you have any questions or require further information, please do not hesitate to reach out.
>
> We are truly grateful for your consideration of our request and look forward to your esteemed reply.
> 
> Kind regards,
> co-founder Shota Kishi
> 
> ELSOUL LABO B.V.
> https://labo.elsoul.nl/

**Comment by KishiTheMechanic** [comment]
Dear @jquast 
I'm writing to offer my sincerest apologies for the unsolicited email. 
I understand now that my approach was inappropriate and intrusive.

I did not intend to cause any inconvenience or imply any unprofessional behavior on my part. My aim was solely to gain invaluable feedback from professionals like you to improve our project. I realize now that my approach did not align with that objective and instead created an inconvenience for you.

I assure you that I will refrain from sending you any further emails and will respect your privacy.

Again, I deeply regret my actions and the inconvenience they may have caused you. I appreciate your understanding on this matter.

Best regards,
Shota Kishi

**Comment by jquast** [comment]
I never volunteered to give you feedback. It is unprofessional behavior only befitting of scammers. You only wish to improve your own project, you care nothing about the people you impact and time you have taken from qualitative work.

**Comment by KishiTheMechanic** [comment]
Dear @jquast ,

I want to sincerely apologize for the inconvenience my previous outreach has caused you. 
I understand that my actions were perceived as unprofessional and self-serving, and for that, I am truly sorry.

I'd like to clarify that my intention was based on the belief that our project, Skeet, has the potential to contribute positively to the global app development ecosystem. 
While my enthusiasm for this project led me to reach out for expert opinions, I now realize that my approach was intrusive and disregarded your time and boundaries.

Thank you for your candid feedback; it has provided me with important perspectives that I had not fully considered. 
I assure you that we will strive to be more respectful of others' time and priorities as we continue to work on improving our project.

I will honor your wish not to be contacted further and thank you again for taking the time to voice your concerns, which we will take to heart.

Best regards,
Shota Kishi

**Comment by jquast** [comment]
It is amazing "CEO" talk to hear you believe that the negative impact you have is secretly a positive one -- and that is not receiving enough recognition!
