### ISSUE TITLE
Unsolicited Promotional Email via GitHub Profile

### ISSUE THREAD

**Issue by eymengunay** [elsoul/skeet-cli#161]
I recently received an unsolicited promotional email from a member of your team, Fumitake Kawasaki, co-founder of ELSOUL LABO B.V.

Here is the content of the email I received:

> I came across your email address on your GitHub profile and thought it would be appropriate to reach out.
I hope this finds you well. My name is Kawasaki, and I am co-founder of ELSOUL LABO B.V.
>
> I observed that you were among the early stars of the jest repository, and this leads me to see you as a developer with exceptional insight and a refined taste in technology.
>
> Recognizing the value of thoughts and feedback from esteemed professionals like yourself, we are reaching out to kindly ask for your expertise.
>
> We would be deeply honored if you could spare a moment to review our serverless framework and share your invaluable insights with us.
>
> Your thoughtful feedback would play a pivotal role in refining our serverless framework, making it more impactful for the tech community.
>
> Please find the link to our GitHub repository here: https://github.com/elsoul/skeet-cli
>
> We fully understand the constraints of your schedule, but any insights or suggestions would be deeply valued.
>
> For any queries or additional information, please feel free to contact us.
> We deeply appreciate your consideration and are excited to hear back from you soon.

I would like to take a moment to clarify the purpose of including my email address on GitHub. Like many others, including myself, I share my email address to facilitate direct communication from individuals who are interested in the repositories I have made publicly available. It serves as a convenient channel for people to reach out with their inquiries, suggestions, or helpful tips.

While I understand the importance of seeking feedback, I believe it's essential to respect the privacy and preferences of GitHub users. Reaching out to users via their email addresses obtained from GitHub profiles for promotional purposes without explicit consent may be considered inappropriate.

I must emphasize that I already receive an excessive amount of unwanted emails on a daily basis and I assume that you do as well. With millions of users and repositories on GitHub just imagine the chaos that would ensue if everyone with a serverless framework started engaging in spamming activities.

I wanted to bring this to your attention, as it reflects on the professional conduct of your team and the image of your project. I am open to constructive communication and collaboration within the GitHub community but I believe it's important to adhere to ethical standards.

Please consider addressing this matter to maintain a positive and respectful environment within the GitHub community and let us not force others to remove their email addresses from their profiles.

**Comment by KishiTheMechanic** [comment]
I wanted to take a moment to apologize for the unsolicited email you recently received from us.

Our intention was to seek your valuable feedback to improve our serverless framework for the benefit of the tech community. 
We did not intend to cause any inconvenience or discomfort.

Again, I apologize for any inconvenience we may have caused and appreciate your understanding.

Best regards,
Shota Kishi
Co-Founder, ELSOUL LABO B.V.

**Comment by eymengunay** [comment]
Framing this outreach as a favor to the tech community is, at best, misleading! 

Your company benefits from the community's contributions, and there's a pressing need for a more transparent dialogue on how these relationships can be genuinely mutually beneficial. Open source is not a one-way street where contributors owe companies their time and insights, especially not through unsolicited emails!

This practice not only borders on being ethically questionable but also raises concerns about potential unlawfulness under the European Union's GDPR, to which, as a company based in the Netherlands, you are subject to. Moreover, such unsolicited outreach may also breach GitHub's terms of service.

Nevertheless, I appreciate your apology and acknowledgment of the situation.
